Added git branch in prompt and time and rm~ed prompt-time.

diff --git a/bashrc_common b/bashrc_common
--- a/bashrc_common
+++ b/bashrc_common
@@ -104,36 +104,56 @@ if [ -f /etc/bash_completion -a -z "$BASH_COMPLETION" ]; then
     . /etc/bash_completion
 fi
 
-# Set the fancy prompt.
-# This is just for bedian
-# set variable identifying the chroot you work in (used in the prompt below)
+# Set the fancy prompt, start by removing what was there.
+PS1="\[\e[00;00m\]"
+# Just for Debian set var with chroot you're in (used in the prompt below)
 if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
-    export debian_chroot=$(cat /etc/debian_chroot)
-    PS1="${debian_chroot:+($debian_chroot)} "
-else
-    PS1=""
+    debian_chroot="$(cat /etc/debian_chroot) "
 fi
+PS1="${debian_chroot:+($debian_chroot)}"
+# Add the return code and time.
+PS1="$PS1"'$? \[\e[00;33m\]\D{%H:%M} '
+# Add (user and) host.
 if [[ "root" == "$USER" ]]; then
-    export PS1="$PS1"'$? \[\033[01;31m\]\h\[\033[01;34m\] \W\$\[\033[00m\] '
+    PS1="$PS1"'\[\e[01;31m\]\h '
 else
-    export PS1="$PS1"'$? \[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ '
+    PS1="$PS1"'\[\e[01;32m\]\u@\h\[\e[00m\]:'
 fi
+# Working dir.
+PS1="$PS1"'\[\e[01;34m\]\W\[\e[00;34m\]'
+# Git branch and dirty.
+function PS1GitBranchDirty {
+    local br
+    br=$(git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')
+    if [[ -z "$br" ]]; then
+        echo ""
+        return 0
+    fi
+    echo -n "[$br"
+    if [[ $(git status 2> /dev/null | tail -n1) != 'nothing to commit (working directory clean)' ]]; then
+        echo -n '*'
+    fi
+    echo "]"
+} 
+export PS1="$PS1"'$(PS1GitBranchDirty)\$\[\e[00m\] '
 
+# Clear the PROMPT_COMMAND
+export PROMPT_COMMAND=""
 # Change the window title of X terminals
 case $TERM in
 	xterm*|rxvt|Eterm|eterm)
-		PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/$HOME/~}\007"'
+		export PROMPT_COMMAND='echo -ne "\e]0;${USER}@${HOSTNAME%%.*}:${PWD/$HOME/~}\007"'
 		;;
 	screen)
-		PROMPT_COMMAND='echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/$HOME/~}\033\\"'
+		export PROMPT_COMMAND='echo -ne "\e_${USER}@${HOSTNAME%%.*}:${PWD/$HOME/~}\e\\"'
 		;;
 esac
 
 # This is my new fancy prompt command.
 # ###    This MUST happen after any other PROMPT_COMMAND things.
-if [ "$TERM" == "screen" ]; then
-	[[ -f "$HOME/profile/prompt_command-time" ]] && . "$HOME/profile/prompt_command-time"
-fi
+#if [ "$TERM" == "screen" ]; then
+	#[[ -f "$HOME/profile/prompt_command-time" ]] && . "$HOME/profile/prompt_command-time"
+#fi
 
 # HISTORY things
 shopt -s histappend
